spring:
    application:
        name: sale
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/saleData?characterEncoding=utf-8
        username: root
        password: 20001120
    data:
      rest:
          base-path: /api
    #        HikariCP连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
            minimum-idle: 10
            maximum-pool-size: 200
            idle-timeout: 60000
            pool-name: MarketingHikariCP
            max-lifetime: 1800000
            connection-timeout: 2000
            connection-test-query: select 1
    jpa:
          show-sql: true  #在控制台打印 sql 语句
    cache:
      type:redis # 指定使用Redis作为缓存管理器
    redis:
      host:127.0.0.1
      port:6379 # Redis服务器端口号
server:
    port:8080

